version: '3.8'

x-meltano-image:
  &meltano-image
  image: meltano-demo-project:dev # Change me to a name:tag that fits the container we will be building
  build: .

x-meltano-env:
  &meltano-env
  MELTANO_DATABASE_URI: 'postgresql://postgres:meltano@meltano-system-db/meltano'
  # Add your meltano .env variables here

# x-airflow-env:
#   &airflow-env
#   AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'postgres://postgres:airflow@airflow-metadata-db/airflow'

services:
  meltano-ui:
    << : *meltano-image
    restart: unless-stopped
    expose:
      - 5000
    volumes:
      - meltano_elt_logs_data:/project/.meltano/logs/elt
    environment:
      << : *meltano-env
    ports:
      - 5000:5000
    command: ui
    depends_on:
      - meltano-system-db
    networks:
      - meltano

  # Meltano system database
  meltano-system-db:
    image: postgres
    restart: unless-stopped
    expose:
      - 5432
    volumes:
      - meltano_postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: meltano # CHANGE ME
      POSTGRES_DB: meltano
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - meltano

  # # Uncomment if you are using the Airflow orchestrator, delete otherwise
  # airflow-webserver:
  #   << : *meltano-image
  #   restart: unless-stopped
  #   depends_on:
  #     - meltano
  #     - meltano-system-db
  #     - airflow-metadata-db
  #   expose:
  #     - 8080
  #   environment:
  #     << : *airflow-env
  #     << : *meltano-env
  #   ports:
  #     - 8080:8080
  #   command: invoke airflow webserver
  #   networks:
  #     - meltano
  #     - airflow
  #
  # airflow-scheduler:
  #   << : *meltano-image
  #   restart: unless-stopped
  #   depends_on:
  #     - meltano
  #     - meltano-system-db
  #     - airflow-metadata-db
  #   expose:
  #     - 8793
  #   volumes:
  #     - meltano_elt_logs_data:/project/.meltano/logs/elt
  #   environment:
  #     << : *airflow-env
  #     << : *meltano-env
  #   command: invoke airflow scheduler
  #   networks:
  #     - meltano
  #     - airflow
  #
  # # Airflow internal database
  # airflow-metadata-db:
  #   image: postgres
  #   restart: unless-stopped
  #   expose:
  #     - 5432
  #   volumes:
  #     - airflow_postgresql_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: airflow # CHANGE ME
  #     POSTGRES_DB: airflow
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #   networks:
  #     - airflow

networks:
  meltano:
  # airflow:

volumes:
  meltano_postgresql_data:
    driver: local
  meltano_elt_logs_data:
    driver: local
  # airflow_postgresql_data:
  #   driver: local
